Manoty/ECO-AFRIQA1

freshly_set/frontend/package-lock.json, freshly_set/frontend/package.json, freshly_set/frontend/src/components/pages/about-us/StriveFor.js
Added some basic animations to the Strive For Section using Animate On Scroll:
Link to docs: https://michalsnik.github.io/aos/
Github Page:  https://github.com/michalsnik/aos
=> minor responsiveness fix and animations

freshly_set/frontend/src/components/pages/about-us/About.js, freshly_set/frontend/src/components/pages/about-us/WhyChoose.js, freshly_set/frontend/src/components/pages/homepage/Faq.js
1. I have refined the faq section
2. added dropdown functionality to the why to choose freshly farms section on about us page
3. Crafted the mobile version of why to choose freshly farms section on about us page
=> The refinements on the contact section and "Why Choose freshly" mobile version

freshly_set/frontend/src/api/blogs.js, freshly_set/frontend/src/components/pages/blogs/BlogForm.jsx, freshly_set/frontend/src/components/pages/blogs/Blogs.js, freshly_set/frontend/src/components/pages/blogs/Contact.js
I have Created the contact section of the blogs page with both desktop and mobile version and refine the code to increase its readability.
What is left:
- Implement the functionality to elicit the user mailing us from the user input
=> The Contact Section of the blogs page

freshly_set/frontend/src/components/pages/farm-produce/HamburgerMenu.js
I have added the following to the hamburger menu of products page
- Transition effect from rihgt to left on opening the menu
- Links to the blogs, about and home page to those pages not yet to be crafted
- Close functionality to th e close bitton
- Hiding of the open button on opening the menu
**What is Left**
- Ingergtating this nav to the top of this page instaed of the former nav used in the previous pages
=> The addition of Links to buttons, transition effect to menu and  functionality to close button

freshly_set/frontend/src/components/Nav/NavAuthenticated.js
I have added the  hamburger menu to the products page
What is left
- Implementing the transition effect on opening the menu
- Fixing some bugs to meet the design
=> The addition of products page hamburger menu

freshly_set/frontend/src/App.js, freshly_set/frontend/src/components/pages/about-us/WhyChoose.js
- I have just fixed the layout for the why choose section in the about page, its mobile version and refinement on the desktop version
- Fixing the error with app.js on repeated calling of predefined variable
=> Fixing the Mobile and Desktop Version of 'Why Choose freshly' section in About page

freshly_set/frontend/src/components/pages/about-us/Hero.js
refined the gif to show properly in the mobile page
=> The refining of mobile version of the hero section of  about page

freshly_set/freshlyapp/models.py, freshly_set/freshlyapp/serializers.py, freshly_set/freshlyapp/urls.py, freshly_set/freshlyapp/views.py, freshly_set/frontend/src/components/pages/SignUp/LoginSignUp.jsx
I made a function in views.py file name as Register to handle signup functionality.
=> added signup integration

freshly_set/frontend/src/App.js, freshly_set/frontend/src/components/footer/FreshlyFooter.js, freshly_set/frontend/src/components/pages/about-us/JoinUs.js, freshly_set/frontend/src/components/pages/blogs/Contact.js, freshly_set/frontend/src/components/pages/cta-detail/ContactUs.js, freshly_set/frontend/src/components/pages/homepage/Contact.js, freshly_set/frontend/src/components/pages/homepage/ContactCard.js, freshly_set/frontend/src/components/pages/homepage/Home.js
I have updated the contact component to contact card for its usability to different sections
What has been done:
- Updated home contact section to fix the allignments and the mobile version
- Reused the card for the Blogs page Contact Section
- Added the contacts cta page
- Linking the contacts CTA page to the "Join Us Today Section in the About Page"
- Linking the contacts CTA page to the Footer Links "COntact us"
=> Updated Contacts Card and Link the Pages

freshly_set/frontend/src/App.js, freshly_set/frontend/src/components/pages/OrderManagement/NotificationCard.js, freshly_set/frontend/src/components/pages/OrderManagement/NotificationList.json, freshly_set/frontend/src/components/pages/OrderManagement/Notifications.js, freshly_set/frontend/src/components/pages/OrderManagement/OrderItemCard.js, freshly_set/frontend/src/components/pages/OrderManagement/OrderItems.json, freshly_set/frontend/src/components/pages/OrderManagement/OrderProgress.js
I have created the Notifications page and link It with the Order Managements Page;
What has Been Implemented
- Desktop and Mobile pages to pull the Notifications and Order list dynamically from the json files.
- The order Progress bars in the pages to show the statusu of the orders
What is Left
- Backend Integration to process the Orders and update the bars status dynamically both in Notifications Page and the Order Progress page
- Backend intergration to create the notifications and its number dynamically
- Backend integration to create the items in the order list for replacing the mock ones in  the json file
=> Notifications Page And Order Managements Page

freshly_set/frontend/src/components/Nav/ProfileSidebar.js, freshly_set/frontend/src/components/pages/profile/PaymentInformation.js
Changes Made:
- Added missed section
=> added payment information tab

freshly_set/frontend/src/components/pages/homepage/Metrics.js, freshly_set/frontend/tailwind.config.js
I have Updated the Metrics to the new design
What has been implemented:
- Adding the Hovering behavior to the desktop version
- Resctricting the clicking on mobile as hovering do not show well
What is left:
- Finding a way to enable hovering behaviour on mobile
=> Metrics Section Refinements to New Design

freshly_set/frontend/src/components/pages/homepage/Services.js, freshly_set/frontend/tailwind.config.js
I have Updated the 'Our Services' Section of the Home Page both the desktop and mobile versions
What have been changed:
- tailwind.config.js file to add the background images for the three cards of the section
- Updating the section to the new design
What is left:
-"**Banner**" and "**Our Reviewers**" sections to wind up refinements to the home page
=> THe updated desktop and Mobile Versions of 'Our Services' Page

freshly_set/frontend/src/components/pages/profile/QuotationHistory.js
The implementation of the Quotation Page UI
What is left:
- Making the Cards Reusable for Updating the data dynamically
=> Quotation History Section of the Profile page, Desktop version

freshly_set/frontend/src/components/Nav/ProfileSidebar.js, freshly_set/frontend/src/components/pages/profile/Help.js, freshly_set/frontend/src/components/pages/profile/Logout.js, freshly_set/frontend/src/components/pages/profile/PrivacyPolicy.js, freshly_set/frontend/src/components/pages/profile/Profile.js, freshly_set/frontend/src/components/pages/profile/TermsConditions.js
I have aadded the support pages on the Navbar and Linking them with the  starter components, also rendering them dynamically on clicking each link
=> Enriching the Sidebar with the Support pages and the Navlinks Appearance

freshly_set/frontend/package-lock.json, freshly_set/frontend/src/components/pages/profile/Transporters.js, freshly_set/frontend/src/components/pages/profile/json/UsersDeliveries.json
The updated transporters section of the profile page with the reusable cards
=> Transporters Section of Profile page, Desktop Version 

freshly_set/frontend/src/components/Nav/Navbar.js, freshly_set/frontend/src/components/pages/cta-detail/Checkout.js
I have updated the Checkout page to resemble the design in both desktop and mobile
also linking the installations page to the navbar dropdown
=> Refinements to te checkout page

freshly_set/frontend/src/components/pages/profile/TermsConditions.js
The implementation  of terms and conditions page of the user profile page
=> The terms and conditions section of Profile page, Desktop version

freshly_set/frontend/src/components/pages/SignUp/LoginSignUp.jsx, freshly_set/frontend/src/components/pages/login/Login.js
I have updated the signup and login pages, the desktop version to resemble the design
What has been implemented:
- Fixing the dimensions and styles to the pages to resemble the design
=> Updated Login and Signup pages, Mobile Versions

freshly_set/frontend/src/components/pages/about-us/TeamCard.js, freshly_set/frontend/src/components/pages/about-us/TeamDetailed.js
I have updated the Detailed Teams Section the Mobile Version
What has been changed,
- The allignments and dimensions for the mobile version
What is left:
- Alligning dynamically the last single card in Executive team and the Tech Team (To be alligned at the centre)
- Restricting the clicking behaviour that mimicry hovering on desktop, as it do not act pricesely on mobile screens
=> The Updated Detailed Teams Section, Mobile version

freshly_set/frontend/package-lock.json, freshly_set/frontend/src/components/pages/farm-produce/FarmingSystemsDetail.js, freshly_set/frontend/src/components/pages/farm-produce/GardenSetupsDetail.js
Updated refined farming system according to the new design
=> farming system

freshly_set/frontend/src/components/Nav/ProfileSidebar.js
I have fixed the bug with imported files so that the project can run
=> Fixing the bug on correcting merge conflict

freshly_set/frontend/src/components/pages/profile/FarmProduceListCard.js, freshly_set/frontend/src/components/pages/profile/FarmSalesListCard.js, freshly_set/frontend/src/components/pages/profile/VerifiedFarmers.js
I have updated the verified farmers UI of the Profile page to be mobile responsive
What has been changed:
- The stylings for the page to resemble the mobile design
What is left:
- Customizing the performance graph to be mobile responsive
=> The Verified Farmers Section of Profile page, Mobile Version

freshly_set/frontend/src/components/pages/profile/Help.js, freshly_set/frontend/src/components/pages/profile/PrivacyPolicy.js
I have updated the UI for the Help section and the Privacy Policy Section of the Profile page
What has been changed:
- The layout for the Help and Privacy pages to resemble the design on Mobile Devices
What is left:
- The implementation for the Mobile Version for the Account Inforrmation, Order History, Quotation History, Transporters and Terms & Conditions sections of the Profile page
=> Help and Privacy Policy Sections of the Profile Page, Mobile Version

freshly_set/frontend/src/App.js, freshly_set/frontend/src/components/pages/homepage/ReviewsDetailed.js, freshly_set/frontend/src/components/pages/homepage/ReviewsDetailedCard.js, freshly_set/frontend/src/components/pages/homepage/json/ReviewsDetailedData.json
I have updated the  detailed reviews section of the home section with the descriptive file name and stylings as well as making the reviews for the mobile and desktop versions
What has been done:
- Fixing the page namings to remove ambiguity
- Fixing the stylings for the pages to resemble the design
- Making the reviwers cards reusable, fetching data from the json file for the reviewer image, name, reviews, review's role and number of start ratings
What is left:
- Making the star ratings update dynamically as per number of provided ratings by the reviewer
- Backend integration to fetch the real data of the reviewers from the database
=> The updated detailed reviews section to make the cards reusable

.idea/.gitignore, .idea/ECO-AFRIQA1.iml, .idea/caches/deviceStreaming.xml, .idea/modules.xml, .idea/vcs.xml, freshly_set/frontend/src/App.js, freshly_set/frontend/src/components/pages/farm-produce/FarmingQuotationMethod.js, freshly_set/frontend/src/components/pages/farm-produce/FarmingSystemSearch.js, freshly_set/frontend/src/components/pages/farm-produce/FarmingSystemsHero.js, freshly_set/frontend/src/components/pages/farm-produce/GardenQuotationMethod.js, freshly_set/frontend/src/components/pages/farm-produce/GardenSetupSearch.js, freshly_set/frontend/src/components/pages/farm-produce/GardenSetupsHero.js, freshly_set/frontend/src/components/pages/farm-produce/json/FarmingSystemSearchEntries.json, freshly_set/frontend/src/components/pages/farm-produce/json/GardenSetupSearchEntries.json
I have added the missing search pages  for the requesting of quotation from the Farming System and Garden Setup and linking them to their respective pages for navigation.
What has been added:
- The UI for search page for the farming systems, desktop and mobile to fetch the data from the json file
- The UI for choice for the method of quotation delivery either by phone or email, desktop and mobile
What is left:
- Enabling the search functionality
- Enabling the filters to filter serach results
- Linking the page to the backend to fetch the real search results and handling the process of quotation delivery to the client based on the delivery method of his or her choice
=> The Missing Search Page for the Farming System and Garden Setup

freshly_set/frontend/src/App.js, freshly_set/frontend/src/components/context/AuthContext.js, freshly_set/frontend/src/components/context/PageContext.js, freshly_set/frontend/src/components/pages/cta-detail/Verified.js, freshly_set/frontend/src/components/pages/farm-produce/CtaPopup.js, freshly_set/frontend/src/components/pages/farm-produce/FarmCard.js, freshly_set/frontend/src/components/pages/farm-produce/FarmingSystemsDetail.js, freshly_set/frontend/src/components/pages/farm-produce/GardenSetupsDetail.js, freshly_set/frontend/src/components/pages/profile/AccountInformation.js, freshly_set/frontend/src/utils/PrivateRoute.js
Fixed Modal Bug for Garden Setups and used mock data to populate modal while backend is being connected
=> Fixed Bug for Garden Setups Page and Updated User Profile Editability

freshly_set/frontend/src/components/Nav/Navbar.js
I have enriched the mobile hamburger menu to make te other pages accessible and styling the icons on the navbar
=> Adding links to the mobile hamburger menu and styling the navbar

freshly_set/frontend/src/components/pages/about-us/WhyChooseDetailed.js
I have updated the page to add the scrolling functionality on clicking the static side bar navs and fixing some issues with layout
=> Updated Why Choose Detail page to add scroll functionality

freshly_set/frontend/src/components/Nav/ProfileSidebar.js, freshly_set/frontend/src/components/pages/profile/AccountInformation.js, freshly_set/frontend/src/components/pages/profile/PaymentInformation.js, freshly_set/frontend/src/components/pages/profile/PrivacyPolicy.js, freshly_set/frontend/src/components/pages/profile/Profile.js
I have updated the Account Information, Payment information, Privacy page, side bar for the profile page (Mobile Version) to resemble the design
=> Updating the Profile Pages for mobile version

freshly_set/frontend/src/components/Nav/ProfileSidebar.js, freshly_set/frontend/src/components/pages/profile/AccountInformation.js, freshly_set/frontend/src/components/pages/profile/Help.js, freshly_set/frontend/src/components/pages/profile/OrderHistory.js, freshly_set/frontend/src/components/pages/profile/OrderHistoryCard.js, freshly_set/frontend/src/components/pages/profile/PaymentInformation.js, freshly_set/frontend/src/components/pages/profile/QuotationHistory.js, freshly_set/frontend/src/components/pages/profile/TermsConditions.js, freshly_set/frontend/src/components/pages/profile/json/QuotationHistoryList.json
I have refined the Quotation history, Terms&Conditions, Order history for the mobile.
And fixing the layout for the other pages on the profile page Desktop  to resemble the design
=> Updated Profile Pages to Resemble the Design

freshly_set/frontend/src/components/pages/cta-detail/Credit.js, freshly_set/frontend/src/components/pages/cta-detail/Mpesa2.js, freshly_set/frontend/src/components/pages/cta-detail/OrderSummary.js
I have updated the Card and Mpesa checkout pages, to improve its layout in desktop and mobile version
=> Happy New Year Devs🎉

freshly_set/frontend/src/components/Nav/Navbar.js, freshly_set/frontend/src/components/Nav/SubNavbar.js, freshly_set/frontend/src/components/pages/about-us/About.js, freshly_set/frontend/src/components/pages/homepage/Hero.js, freshly_set/frontend/src/components/pages/homepage/Home.js
I have fixed the allignments for the homaoage and about page navbar and subnavbars for the cropped contents
=> Fixing Navbar and Subnavbars on mobile
